### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Коды ошибок для настраиваемой функции. Коды ошибок будут отображаться в ячейке, вызываемой функцией.


  В дополнение к этим кодам ошибок отображаются настраиваемые сообщения об ошибке. Настраиваемые сообщения отображаются в меню индикатора ошибок, к которому можно получить доступ, зависая над флагом ошибки на каждой ячейке с ошибкой.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает, что используемая функция делится на нулевые или пустые ячейки. Пользовательское сообщение об ошибке нельзя использовать. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что в имени функции имеется опечатка. Обратите внимание, что этот код ошибки поддерживается как настраиваемая ошибка ввода функции, но не как настраиваемая ошибка вывода функции. Пользовательское сообщение об ошибке нельзя использовать. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что в функции существует проблема с номером. Пользовательское сообщение об ошибке нельзя использовать. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает, что функция относится к недействительной ячейке. Обратите внимание, что этот код ошибки поддерживается как настраиваемая ошибка ввода функции, но не как настраиваемая ошибка вывода функции. Пользовательское сообщение об ошибке нельзя использовать. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает, что значение в функции имеет неправильный тип данных. При желании в дополнение к коду ошибки можно использовать пользовательское сообщение об ошибке. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает, что функция или служба недоступны. При желании в дополнение к коду ошибки можно использовать пользовательское сообщение об ошибке. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что диапазоны функции не пересекаются. Пользовательское сообщение об ошибке нельзя использовать. \[[Набор API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: 2c8673b5e49abbb312138d3436da25613d17df74
  ms.sourcegitcommit: a8a86cfcaff5ad7dacc653d63502c76b1fedbebe
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 03/26/2021
  ms.locfileid: "51233457"
