### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Коды ошибок для пользовательских функций. Коды ошибок будут отображаться в ячейке, вызвавшей функцию.


  В дополнение к этим кодам ошибок отображаются настраиваемые сообщения об ошибках. Настраиваемые сообщения отображаются в меню индикации ошибки, доступ к которому осуществляется при наведении курсора на флаг ошибки в каждой ячейке с ошибкой.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что используемая функция делится на ноль или пустые ячейки. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на наличие опечатки в имени функции. Обратите внимание, что этот код ошибки поддерживается как ошибка ввода пользовательской функции, но не в качестве ошибки вывода пользовательской функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на наличие проблемы с числом в функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что функция ссылается на недопустимую ячейку. Обратите внимание, что этот код ошибки поддерживается как ошибка ввода пользовательской функции, но не в качестве ошибки вывода пользовательской функции. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что значение в функции имеет неверный тип данных. При необходимости можно использовать настраиваемое сообщение об ошибке в дополнение к коду ошибки. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что функция или служба недоступна. При необходимости можно использовать настраиваемое сообщение об ошибке в дополнение к коду ошибки. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Этот код ошибки указывает на то, что диапазоны функции не пересекаются. Настраиваемое сообщение об ошибке не может быть использовано. \[[Набор API: кустомфунктионсрунтиме 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: cec80f674bc573e3e3d3679ab96792ea5e469ce3
  ms.sourcegitcommit: a6ecbc9abca2ab5c82af4c869e3e2d72c999a4c1
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "49542049"
